sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t renanmach/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true renanmach/react-test npm test

after_success:
  - docker build -t renanmach/multi-client ./client
  - docker build -t renanmach/multi-nginx ./nginx
  - docker build -t renanmach/multi-server ./server
  - docker build -t renanmach/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push renanmach/multi-client
  - docker push renanmach/multi-nginx
  - docker push renanmach/multi-server
  - docker push renanmach/multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: 'us-east-1'
#  app: 'multi-docker'
#  env: 'MultiDocker-env'
#  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#  bucket_path: 'docker-multi'
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
